codecov:
  require_ci_to_pass: yes
  strict_yaml_branch: master

coverage:
  precision: 2
  round: down
  range: "60...80"
  status:
    project:
      default:
        # basic
        target: 60
        threshold: 1
        base: auto 
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no